parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - prettier
env:
  commonjs: true
  node: true
  mocha: true
settings:
  import/core-modules: [electron]
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - airbnb-base
  - airbnb-typescript/base
rules:
  '@typescript-eslint/comma-dangle': 0
  no-console: 1
  '@typescript-eslint/indent': 0
  implicit-arrow-linebreak: 0
  operator-linebreak: 0
  arrow-body-style: 0
  import/prefer-default-export: 0
  '@typescript-eslint/no-unused-vars': 1
  '@typescript-eslint/no-explicit-any': 0
  function-paren-newline: 0
  no-param-reassign: 0
  no-restricted-syntax:
    - error
    - ForInStatement
    - LabeledStatement
    - WithStatement
  object-curly-newline: 0
  import/no-absolute-path: 0
  import/extensions:
    - 0
    - ts: never
