name: Security audit

on:
  push:
    branches:
      - master

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install npm
        run: npm install
      - name: Security audit
        run: npm run security-audit